### Data Manipulation and Analysis with Pandas
##### Data manipulation and analysis are key tasks in any data science or data analysis project. Pandas provides a wide range of functions for data manipulation and analysis, making it easier to clean, transform, and extract insights from data. In this lesson, we will cover various data manipulation and analysis techniques using Pandas.

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('sales_practice_dataset.csv')

## fetch the first 5 row
df.head(5)

         Date Category  Value   Product  Sales Region
0  2023-01-01        C    3.0  Product1  525.0  South
1  2023-01-02        A   31.0  Product2  646.0   West
2  2023-01-03        C   40.0  Product2  401.0  South
3  2023-01-04        C   36.0  Product2  680.0   West
4  2023-01-05        A   24.0  Product2  448.0   West

In [3]:
df.tail(5)

           Date Category  Value   Product  Sales Region
995  2025-09-22        B    6.0  Product3  756.0  North
996  2025-09-23        B    9.0  Product1  474.0   West
997  2025-09-24        C    6.0  Product3  261.0  South
998  2025-09-25        C   73.0  Product1    NaN  North
999  2025-09-26        A   95.0  Product3  479.0   East

In [4]:
df.describe()

            Value       Sales
count  960.000000  960.000000
mean    49.721875  566.967708
std     28.983127  251.630379
min      1.000000  100.000000
25%     25.000000  361.000000
50%     49.000000  577.000000
75%     75.000000  771.250000
max     99.000000  998.000000

In [5]:
df.dtypes

Date         object
Category     object
Value       float64
Product      object
Sales       float64
Region       object
dtype: object

In [6]:
## Handing Missing Values

df.isnull()

      Date  Category  Value  Product  Sales  Region
0    False     False  False    False  False   False
1    False     False  False    False  False   False
2    False     False  False    False  False   False
3    False     False  False    False  False   False
4    False     False  False    False  False   False
..     ...       ...    ...      ...    ...     ...
995  False     False  False    False  False   False
996  False     False  False    False  False   False
997  False     False  False    False  False   False
998  False     False  False    False   True   False
999  False     False  False    False  False   False

[1000 rows x 6 columns]

In [7]:
df[df.isnull()]

    Date Category  Value Product  Sales Region
0    NaN      NaN    NaN     NaN    NaN    NaN
1    NaN      NaN    NaN     NaN    NaN    NaN
2    NaN      NaN    NaN     NaN    NaN    NaN
3    NaN      NaN    NaN     NaN    NaN    NaN
4    NaN      NaN    NaN     NaN    NaN    NaN
..   ...      ...    ...     ...    ...    ...
995  NaN      NaN    NaN     NaN    NaN    NaN
996  NaN      NaN    NaN     NaN    NaN    NaN
997  NaN      NaN    NaN     NaN    NaN    NaN
998  NaN      NaN    NaN     NaN    NaN    NaN
999  NaN      NaN    NaN     NaN    NaN    NaN

[1000 rows x 6 columns]

In [8]:
df.isnull().any()

Date        False
Category    False
Value        True
Product     False
Sales        True
Region      False
dtype: bool

In [9]:
df.isnull().any(axis = 1)

0      False
1      False
2      False
3      False
4      False
       ...
995    False
996    False
997    False
998     True
999    False
Length: 1000, dtype: bool

In [10]:
df.isnull().sum()

Date         0
Category     0
Value       40
Product      0
Sales       40
Region       0
dtype: int64

In [11]:
df.fillna(0)

           Date Category  Value   Product  Sales Region
0    2023-01-01        C    3.0  Product1  525.0  South
1    2023-01-02        A   31.0  Product2  646.0   West
2    2023-01-03        C   40.0  Product2  401.0  South
3    2023-01-04        C   36.0  Product2  680.0   West
4    2023-01-05        A   24.0  Product2  448.0   West
..          ...      ...    ...       ...    ...    ...
995  2025-09-22        B    6.0  Product3  756.0  North
996  2025-09-23        B    9.0  Product1  474.0   West
997  2025-09-24        C    6.0  Product3  261.0  South
998  2025-09-25        C   73.0  Product1    0.0  North
999  2025-09-26        A   95.0  Product3  479.0   East

[1000 rows x 6 columns]

In [12]:
df_filled = df.fillna(0)

In [13]:
### Filling missing values with the mean of the column

df['Sales_fillNA'] = df['Sales'].fillna(df['Sales'].mean())
df

           Date Category  Value   Product  Sales Region  Sales_fillNA
0    2023-01-01        C    3.0  Product1  525.0  South    525.000000
1    2023-01-02        A   31.0  Product2  646.0   West    646.000000
2    2023-01-03        C   40.0  Product2  401.0  South    401.000000
3    2023-01-04        C   36.0  Product2  680.0   West    680.000000
4    2023-01-05        A   24.0  Product2  448.0   West    448.000000
..          ...      ...    ...       ...    ...    ...           ...
995  2025-09-22        B    6.0  Product3  756.0  North    756.000000
996  2025-09-23        B    9.0  Product1  474.0   West    474.000000
997  2025-09-24        C    6.0  Product3  261.0  South    261.000000
998  2025-09-25        C   73.0  Product1    NaN  North    566.967708
999  2025-09-26        A   95.0  Product3  479.0   East    479.000000

[1000 rows x 7 columns]

In [14]:
df.dtypes

Date             object
Category         object
Value           float64
Product          object
Sales           float64
Region           object
Sales_fillNA    float64
dtype: object

In [15]:
## Renaming Columns

df = df.rename(columns = {'Date' : 'Sales Date'})
df.head()

   Sales Date Category  Value   Product  Sales Region  Sales_fillNA
0  2023-01-01        C    3.0  Product1  525.0  South         525.0
1  2023-01-02        A   31.0  Product2  646.0   West         646.0
2  2023-01-03        C   40.0  Product2  401.0  South         401.0
3  2023-01-04        C   36.0  Product2  680.0   West         680.0
4  2023-01-05        A   24.0  Product2  448.0   West         448.0

In [16]:
## CHange Datatypes

df['Value_new'] = df['Value'].astype(float)
df.head()

   Sales Date Category  Value   Product  Sales Region  Sales_fillNA  Value_new
0  2023-01-01        C    3.0  Product1  525.0  South         525.0        3.0
1  2023-01-02        A   31.0  Product2  646.0   West         646.0       31.0
2  2023-01-03        C   40.0  Product2  401.0  South         401.0       40.0
3  2023-01-04        C   36.0  Product2  680.0   West         680.0       36.0
4  2023-01-05        A   24.0  Product2  448.0   West         448.0       24.0

In [17]:
df['Value_new'] = df['Value'].astype(int)
df.head()

IntCastingNaNError: Cannot convert non-finite values (NA or inf) to integer

##### Showing Error because in the'Value' column there are some missing values

In [18]:
df['Value_new'] = df['Value'].fillna(df['Value'].mean()).astype(int)
df.head()

   Sales Date Category  Value   Product  Sales Region  Sales_fillNA  Value_new
0  2023-01-01        C    3.0  Product1  525.0  South         525.0          3
1  2023-01-02        A   31.0  Product2  646.0   West         646.0         31
2  2023-01-03        C   40.0  Product2  401.0  South         401.0         40
3  2023-01-04        C   36.0  Product2  680.0   West         680.0         36
4  2023-01-05        A   24.0  Product2  448.0   West         448.0         24

In [19]:
df['New Value'] = df['Value'].apply(lambda x:x*2)
df.head()

,Sales Date,Category,Value,Product,Sales,Region,Sales_fillNA,Value_new,New Value
0,2023-01-01,C,3.0,Product1,525.0,South,525.0,3,6.0
1,2023-01-02,A,31.0,Product2,646.0,West,646.0,31,62.0
2,2023-01-03,C,40.0,Product2,401.0,South,401.0,40,80.0
3,2023-01-04,C,36.0,Product2,680.0,West,680.0,36,72.0
4,2023-01-05,A,24.0,Product2,448.0,West,448.0,24,48.0

Bhai lambda function ka main purpose hai chhota aur simple function ko ek hi line me likhna, bina def use kiye.

Matlab jab function bahut simple ho aur ek hi baar use karna ho, tab lambda use karte hain.

🧠 Lambda ki limitations

1️⃣ Sirf one expression likh sakte ho
2️⃣ Multiple statements nahi likh sakte
3️⃣ Complex logic ke liye def better hai

In [20]:
## Data Aggregating And Grouping

df.head()

,Sales Date,Category,Value,Product,Sales,Region,Sales_fillNA,Value_new,New Value
0,2023-01-01,C,3.0,Product1,525.0,South,525.0,3,6.0
1,2023-01-02,A,31.0,Product2,646.0,West,646.0,31,62.0
2,2023-01-03,C,40.0,Product2,401.0,South,401.0,40,80.0
3,2023-01-04,C,36.0,Product2,680.0,West,680.0,36,72.0
4,2023-01-05,A,24.0,Product2,448.0,West,448.0,24,48.0

In [21]:
grouped_mean = df.groupby('Product')['Value'].mean()
print(grouped_mean)

Product
Product1    50.252308
Product2    47.850299
Product3    51.225914
Name: Value, dtype: float64

In [23]:
grouped_sum = df.groupby(['Product','Region'])['Value'].sum()
print(grouped_sum)

Product   Region
Product1  East      4754.0
          North     3539.0
          South     4263.0
          West      3776.0
Product2  East      3899.0
          North     3878.0
          South     4329.0
          West      3876.0
Product3  East      4634.0
          North     4316.0
          South     3167.0
          West      3302.0
Name: Value, dtype: float64

In [22]:
df.groupby(['Product','Region'])['Value'].mean()

Product   Region
Product1  East      53.415730
          North     50.557143
          South     47.898876
          West      49.038961
Product2  East      51.986667
          North     47.292683
          South     47.054348
          West      45.600000
Product3  East      52.659091
          North     55.333333
          South     50.269841
          West      45.861111
Name: Value, dtype: float64

In [26]:
df.groupby(['Region','Product'])['Value'].mean()

Region  Product
East    Product1    53.415730
        Product2    51.986667
        Product3    52.659091
North   Product1    50.557143
        Product2    47.292683
        Product3    55.333333
South   Product1    47.898876
        Product2    47.054348
        Product3    50.269841
West    Product1    49.038961
        Product2    45.600000
        Product3    45.861111
Name: Value, dtype: float64

In [25]:
## Aggregate Multiple Functions

grouped_agg = df.groupby('Region')['Value'].agg(['mean','sum','count'])
print(grouped_agg)

             mean      sum  count
Region
East    52.726190  13287.0    252
North   51.013043  11733.0    230
South   48.192623  11759.0    244
West    46.811966  10954.0    234

In [29]:
### Merging and joining Dataframes
# Create sample DataFrames

df1 = pd.DataFrame({'Key':['A','B','C'], 'Value1':[1,2,3]})
df2 = pd.DataFrame({'Key':['A','B','D'], 'Value2':[4,5,6]})

In [30]:
df1

  Key  Value1
0   A       1
1   B       2
2   C       3

In [31]:
df2

  Key  Value2
0   A       4
1   B       5
2   D       6

In [32]:
## Merge Dataframes on the 'Key Column'

pd.merge(df1,df2)

  Key  Value1  Value2
0   A       1       4
1   B       2       5

In [33]:
pd.merge(df1,df2, on="Key", how="inner")

  Key  Value1  Value2
0   A       1       4
1   B       2       5

In [34]:
pd.merge(df1,df2, on="Key", how="outer")

  Key  Value1  Value2
0   A     1.0     4.0
1   B     2.0     5.0
2   C     3.0     NaN
3   D     NaN     6.0

In [35]:
pd.merge(df1, df2, on="Key", how="left")

  Key  Value1  Value2
0   A       1     4.0
1   B       2     5.0
2   C       3     NaN

In [36]:
pd.merge(df1, df2, on="Key", how="right")

  Key  Value1  Value2
0   A     1.0       4
1   B     2.0       5
2   D     NaN       6